services:
  # PostgreSQL with PostGIS and TimescaleDB
  postgres:
    image: timescale/timescaledb:2.11.2-pg14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: essg
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      postgres -c shared_preload_libraries=timescaledb
    restart: always

  # NATS message broker
  nats:
    image: nats:2.9
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--jetstream"]
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 4222"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ESSG API server
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=essg
      - DB_SSL_MODE=disable
      - NATS_URL=nats://nats:4222
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy

volumes:
  postgres-data: